### ISSUE TITLE
Cannot reach server

### ISSUE THREAD

**Issue by viamin** [ngovil21/Plex-Cleaner#36]
After updating to the latest version, I am seeing an unhelpful error message: 'Cannot reach server!'

I can reach my Plex server at the host and port in the config, and I'm not using PlexHome or any local username and password. 

[cleaner.log.txt](https://github.com/ngovil21/Plex-Cleaner/files/862111/cleaner.log.txt)

**Comment by ngovil21** [comment]
That error means that the plexscript cannot reach your plex server. It looks like you are running the script on your VPN subnet. Please check to make sure that your firewall lets python access that ip address if you have one. Also try generating a new token and running the script with the new token.

Otherwise you can run the script with the `--debug --test` parameters which should give the actual error and more information.

**Comment by viamin** [comment]
Turning on --debug shows a 401 unauthorized. Adding my plex credentials (later using the token) fixed this. Is this a new requirement? I'm not using PlexHome and login wasn't required in earlier versions of Plex-Cleaner (or maybe by Plex server). Closing in any case since the config file change fixed this.

**Comment by ngovil21** [comment]
Sometimes the Plex token will get invalidated by the server and need to be refreshed. Using your username and password will allow a new token to be generated. You should then be able to use the new token with the script.
