### ISSUE TITLE
finding files similar to: 

### ISSUE THREAD

**Issue by dejected1** [ngovil21/Plex-Cleaner#41]
When running the script, when it finds a match, there is a long pause and it says : "Finding files similar to: \my network location."

I have set this  "similar_files": false. No change. then true just for giggles. Same result. everything is working, there is just that pause. 

Is this business as usual or can i speed it up?
newest master version of script, cloned today. windows 10.

**Comment by ngovil21** [comment]
There was an error in the code that ignored the Config file setting for `similar_files`, which has been fixed now (0c5c7644f0599cdaf409aafd8102bb6c886a33ee). Thanks for pointing it out!

The delay is likely due to listing files over the network connection. If you are okay disabling the setting, then it should perform faster.
