### ISSUE TITLE
Issues Decoding ASCII Characters

### ISSUE THREAD

**Issue by LarsaSolidor** [ngovil21/Plex-Cleaner#45]
If I have shows in my Plex library which contain accented characters, then the script fails due to an ASCII decode error. 

```
Star Trek: The Next Generation - S03xE013 - D?j? Q | Viewed: 1 | Days Since Last Viewed: 5 | On Deck: False
Traceback (most recent call last):
  File "PlexCleaner.py", line 1158, in <module>
    changed += checkShow(DirectoryNode)
  File "PlexCleaner.py", line 856, in checkShow
    location=show_settings['location']):
  File "PlexCleaner.py", line 418, in performAction
    if file.startswith(path):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 86: ordinal not in range(128)
```

Deleting these shows from my library resolves this issue but is not ideal.

**Comment by M0UL** [comment]
try running the script with --reload_encoding

**Comment by ngovil21** [comment]
Or try running the script with python3 if possible.

**Comment by NetEng-BuzB** [comment]
Not sure if it's appropriate to comment on a closed case, but I've tried both of the recommendations provided above and neither is resolving the issue of special characters.  

Running with --test option flags several files, but removing the --test option causes it to fail with the following errors:

Hawaii Five-0 - S07xE005 - Ke K? ?Ana | Viewed: 1 | Days Since Last Viewed: 170 | On Deck: False
Finding files similar to: /Volumes/BuzB-Data/PlexMedia/Television/New/Hawaii Five-0 (2010)/Season 07/Hawaii Five-0 - S07E05 - Ke K? ?Ana*
Traceback (most recent call last):
  File "/Users/buzb/Scripts/PlexCleaner/PlexCleaner.py", line 1169, in <module>
    changed += checkShow(DirectoryNode)
  File "/Users/buzb/Scripts/PlexCleaner/PlexCleaner.py", line 865, in checkShow
    location=show_settings['location']):
  File "/Users/buzb/Scripts/PlexCleaner/PlexCleaner.py", line 489, in performAction
    ActionHistory.append("[MOVED] " + filelist[0])
IndexError: list index out of range

**Comment by ngovil21** [comment]
That issue does not look to actually be because of invalid characters. Does
the video file at /Volumes/BuzB-Data/PlexMedia/Television/New/Hawaii Five-0
(2010)/Season 07/Hawaii Five-0 - S07E05 - Ke K? ?Ana actually exist? If the
file was already deleted then that might be the issue. Try running Empty
Trash on the Plex Library and re-running. I will add a check to prevent the
issue.

**Comment by NetEng-BuzB** [comment]
Agree, the error is different and I thought I pulled my comment before it got submitted.

The files did exist, so I deleted the library, emptied the trash, then recreated the library.  Again PlexCleaner stopped with the same error, so I configured Plex to delete that one series' files 7 days after watching.  PlexCleaner then was able to clean other files with special characters.

Get Outlook for Android<https://aka.ms/ghei36>
