### ISSUE TITLE
Integrating the script in a web service

### ISSUE THREAD

**Issue by NitriKx** [ngovil21/Plex-Cleaner#60]
I would like to know if integrating this script in a web service (to configure it) would be interesting or not? 

In the case it is, should I push the sources in this repo? Or create separated repo that uses this repo (submodule)?

**Comment by JohanSF** [comment]
As a user of this script, this is high on my wish list.

I would love for this script to have a modern selfhosted configuration and stats page. All packaged in a docker. Oh, and it should be easy to reverse proxy. Please make this happen!

**Comment by LSL1337** [comment]
most def.

**Comment by ngovil21** [comment]
Seems like there are some people who would like a web service. I don't mind you using the script as a module. I would like it separate though because I have made sure to keep this script as widely usable without the need for any external libraries.

For a webserver you would likely use something Flask or Django.
